// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crmbutagpkaaenfxvina.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybWJ1dGFncGthYWVuZnh2aW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzQ3NzksImV4cCI6MjA3MjQxMDc3OX0.V7eAtPV68GdNdy1855uF7jIkjsGWxgLwxSjHbGM0b6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});